### ISSUE TITLE
Non-touchscreen devices

### ISSUE THREAD

**Issue by ferrellsl** [AlynxZhou/flipclock-android#1]
I'm using your flipclock on a Chromebook that doesn't have a touch screen so I have no way to toggle the seconds on/off.  Could you add a keyboard combination such as Ctrl-S for example to toggle the seconds?  Thanks.  Love your work by the way.

**Comment by AlynxZhou** [comment]
https://github.com/AlynxZhou/flipclock/blob/master/srcs/flipclock.c#L892-L895

Press Esc or q to exit.

Press s to toggle second.

Press f to toggle fullscreen.

Press t to toggle 12/24-hour clock format.
