### ISSUE TITLE
Suggestions for supporting lower versions of Android

### ISSUE THREAD

**Issue by glenlau228** [AlynxZhou/flipclock-android#2]
Because the mobile phones that use mobile phones as clocks are all obsolete old mobile phones, they can no longer update the system, and they often use very low versions of Android systems, such as Android 2.3. Can you provide support for these very old mobile phones, thank you very much.

**Comment by AlynxZhou** [comment]
That is decided by SDL, SDK version 16 (Android 4.1) is relatively old, 2.3 is too old and it may not support some features SDL needs, I cannot do this.
